import {
    Activity,
    Bot,
    Building,
    Cable,
    Calendar,
    CalendarDays,
    Circle,
    Clapperboard,
    FileBadge,
    FileCode,
    FileJson,
    FileText,
    Gauge,
    GitBranch,
    Globe,
    IdCard,
    Inbox,
    Key,
    KeyRound,
    Layers,
    LayoutDashboard,
    Link2,
    ListChecks,
    Mail,
    Map,
    MessagesSquare,
    NotebookPen,
    Package,
    Receipt,
    Mic,
    Repeat,
    Scale,
    Send,
    Server,
    Shapes,
    ShieldCheck,
    Sliders,
    Target,
    UserCog,
    Users,
    Webhook,
    Workflow,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * The nav icon map — the third name→component binding beside frame's route and widget registries: the
 * server declares an icon by NAME (`#[ParticleResource]`'s `nav.icon`, and the section's own), the host
 * binds each name to a component here.
 *
 * Deliberately an explicit map and NOT `import * as Lucide` + a kebab→Pascal lookup: the namespace
 * import defeats tree-shaking and drags the whole icon set into the production bundle. An unmapped name
 * falls back to a neutral dot rather than rendering nothing, so a new declaration is visibly unstyled
 * instead of invisibly iconless.
 *
 * Both casings are keyed because the wire carries both: resource seats emit kebab-case
 * (`file-text`), section seats emit PascalCase (`FileText`).
 */
const ICONS: Record<string, LucideIcon> = {
    'file-text': FileText,
    FileText,
    'file-json': FileJson,
    FileJson,
    'git-branch': GitBranch,
    GitBranch,
    globe: Globe,
    Globe,
    map: Map,
    Map,
    server: Server,
    Server,
    users: Users,
    Users,
    webhook: Webhook,
    Webhook,
    'key-round': KeyRound,
    KeyRound,
    link: Link2,
    Link2,
    // The operator rail's seat (laravel-tower-starter's `platform` section).
    activity: Activity,
    Activity,
    bot: Bot,
    Bot,
    building: Building,
    Building,
    cable: Cable,
    Cable,
    gauge: Gauge,
    Gauge,
    'layout-dashboard': LayoutDashboard,
    LayoutDashboard,
    // Every other name a live `#[ParticleResource]` declaration in the estate carries (beam-accounts,
    // beam-calendars, beam-commerce, beam-notifications, beam-workflows, satellite-composition, tower,
    // beam-extension-demo). A name lucide does not export (`microphone`) stays on the neutral dot.
    calendar: Calendar,
    Calendar,
    'calendar-days': CalendarDays,
    CalendarDays,
    clapperboard: Clapperboard,
    Clapperboard,
    'file-badge': FileBadge,
    FileBadge,
    'file-code': FileCode,
    FileCode,
    'id-card': IdCard,
    IdCard,
    inbox: Inbox,
    Inbox,
    key: Key,
    Key,
    layers: Layers,
    Layers,
    'list-checks': ListChecks,
    ListChecks,
    mail: Mail,
    Mail,
    'messages-square': MessagesSquare,
    MessagesSquare,
    'notebook-pen': NotebookPen,
    NotebookPen,
    package: Package,
    Package,
    receipt: Receipt,
    Receipt,
    mic: Mic,
    Mic,
    repeat: Repeat,
    Repeat,
    scale: Scale,
    Scale,
    send: Send,
    Send,
    shapes: Shapes,
    Shapes,
    'shield-check': ShieldCheck,
    ShieldCheck,
    sliders: Sliders,
    Sliders,
    target: Target,
    Target,
    'user-cog': UserCog,
    UserCog,
    workflow: Workflow,
    Workflow,
};

export function frameIcon(name: string | null | undefined): LucideIcon {
    return (name ? ICONS[name] : undefined) ?? Circle;
}
