import { defineConfig } from "tsup";
export default defineConfig({
  entry: ["src/index.tsx"],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  splitting: true,
  clean: true,
  external: [
    "@inertiajs/core",
    "@inertiajs/react",
    "@laravel/passkeys",
    "@radix-ui/react-avatar",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-collapsible",
    "@radix-ui/react-dialog",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-label",
    "@radix-ui/react-navigation-menu",
    "@radix-ui/react-select",
    "@radix-ui/react-separator",
    "@radix-ui/react-slot",
    "@radix-ui/react-toggle",
    "@radix-ui/react-toggle-group",
    "@radix-ui/react-tooltip",
    "@schemastud/frame",
    "@schemastud/mainframe",
    "@schemastud/seam",
    "@schemastud/ui",
    "@splicewire/beam-accounts",
    "@splicewire/beam-mainframe",
    "@splicewire/beam-ux",
    "@tanstack/react-query",
    "class-variance-authority",
    "clsx",
    "input-otp",
    "lucide-react",
    "react",
    "react-router",
    "sonner",
    "tailwind-merge",
    "@splicewire/beam-resources",
  ],
});
